/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.SQLite;
import Model.Product;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author beepxD
 */
public class MgmtProduct extends javax.swing.JPanel {

    public SQLite sqlite;
    public DefaultTableModel tableModel;
    String username;
    int userRole;
    private boolean isProductValValid = false;
    private int cntSimilarProd = 0;
    
    public MgmtProduct(SQLite sqlite, int role, String username) {
        initComponents();
        this.sqlite = sqlite;
        tableModel = (DefaultTableModel)table.getModel();
        table.getTableHeader().setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 14));
        this.username = username;
        this.userRole = role;
    }

    public void init(){
        //      CLEAR TABLE
        for(int nCtr = tableModel.getRowCount(); nCtr > 0; nCtr--){
            tableModel.removeRow(0);
        }
        
        //      LOAD CONTENTS
        ArrayList<Product> products = sqlite.getProduct();
        for(int nCtr = 0; nCtr < products.size(); nCtr++){
            tableModel.addRow(new Object[]{
                products.get(nCtr).getName(), 
                products.get(nCtr).getStock(), 
                products.get(nCtr).getPrice()});
        }
        
        //      Set buttons
        switch(userRole) {
            case 2:   // Client
                purchaseBtn.setVisible(true);
                addBtn.setVisible(false);
                editBtn.setVisible(false);
                deleteBtn.setVisible(false);
                break;
            case 3:   // Staff
                addBtn.setVisible(true);
                editBtn.setVisible(true);
                deleteBtn.setVisible(true);
                purchaseBtn.setVisible(false);
                break;
            case 4:   // Manager
                addBtn.setVisible(true);
                editBtn.setVisible(true);
                deleteBtn.setVisible(true);
                purchaseBtn.setVisible(false);
                break;
        }  
    }
    
    public void designer(JTextField component, String text){
        component.setSize(70, 600);
        component.setFont(new java.awt.Font("Tahoma", 0, 18));
        component.setBackground(new java.awt.Color(240, 240, 240));
        component.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        component.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), text, javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12)));
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        purchaseBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        table.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Stock", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(24);
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(50);
            table.getColumnModel().getColumn(1).setMaxWidth(100);
            table.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        purchaseBtn.setBackground(new java.awt.Color(255, 255, 255));
        purchaseBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        purchaseBtn.setText("PURCHASE");
        purchaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseBtnActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(255, 255, 255));
        addBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(255, 255, 255));
        editBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editBtn.setText("EDIT");
        editBtn.setToolTipText("");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 255, 255));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(purchaseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purchaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void purchaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseBtnActionPerformed
        if(table.getSelectedRow() >= 0){
            JTextField stockFld = new JTextField("0");
            designer(stockFld, "PRODUCT STOCK");

            Object[] message = {
                "How many " + tableModel.getValueAt(table.getSelectedRow(), 0) + " do you want to purchase?", stockFld
            };

            int result = JOptionPane.showConfirmDialog(null, message, "PURCHASE PRODUCT", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null);

            Product prod = sqlite.getProduct((String)tableModel.getValueAt(table.getSelectedRow(), 0));
            
            if (result == JOptionPane.OK_OPTION) {
                System.out.println(stockFld.getText());
                sqlite.editProduct(prod, prod.getName(), prod.getStock() - Integer.parseInt(stockFld.getText()), prod.getPrice());
                sqlite.addHistory(this.username, prod.getName(), Integer.parseInt(stockFld.getText()), new Timestamp(new Date().getTime()).toString());
                this.init();
            }
        }
    }//GEN-LAST:event_purchaseBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        JTextField nameFld = new JTextField();
        JTextField stockFld = new JTextField();
        JTextField priceFld = new JTextField();

        designer(nameFld, "PRODUCT NAME");
        designer(stockFld, "PRODUCT STOCK");
        designer(priceFld, "PRODUCT PRICE");

        Object[] message = {
            "Insert New Product Details:", nameFld, stockFld, priceFld
        };

        int result = JOptionPane.showConfirmDialog(null, message, "ADD PRODUCT", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null);

        /*if (result == JOptionPane.OK_OPTION) {
            System.out.println(nameFld.getText());
            System.out.println(stockFld.getText());
            System.out.println(priceFld.getText());
            
            checkProduct(nameFld.getText(), stockFld.getText(), priceFld.getText());
            sqlite.addProduct((String)nameFld.getText(), Integer.parseInt(stockFld.getText()), Double.parseDouble(priceFld.getText()));
            this.init();
        }*/
        
        if (result == JOptionPane.OK_OPTION) {
            checkProduct(nameFld.getText(), stockFld.getText(), priceFld.getText());
            checkExistingProduct(1, nameFld.getText(), "temp_value");
            
            if(isProductValValid && cntSimilarProd == 0){
                System.out.println(nameFld.getText());
                System.out.println(stockFld.getText());
                System.out.println(priceFld.getText());
                sqlite.addProduct((String)nameFld.getText(), Integer.parseInt(stockFld.getText()), Double.parseDouble(priceFld.getText()));
                this.init();
            } 
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        if(table.getSelectedRow() >= 0){
            JTextField nameFld = new JTextField(tableModel.getValueAt(table.getSelectedRow(), 0) + "");
            JTextField stockFld = new JTextField(tableModel.getValueAt(table.getSelectedRow(), 1) + "");
            JTextField priceFld = new JTextField(tableModel.getValueAt(table.getSelectedRow(), 2) + "");

            designer(nameFld, "PRODUCT NAME");
            designer(stockFld, "PRODUCT STOCK");
            designer(priceFld, "PRODUCT PRICE");

            Object[] message = {
                "Edit Product Details:", nameFld, stockFld, priceFld
            };
            
            Product product = sqlite.getProduct((String)tableModel.getValueAt(table.getSelectedRow(), 0));

            int result = JOptionPane.showConfirmDialog(null, message, "EDIT PRODUCT", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null);
            
            if (result == JOptionPane.OK_OPTION) {
                checkProduct(nameFld.getText(), stockFld.getText(), priceFld.getText());
                checkExistingProduct(2, nameFld.getText(), product.getName());
                
                if(isProductValValid){
                    System.out.println(nameFld.getText());
                    System.out.println(stockFld.getText());
                    System.out.println(priceFld.getText());
                    sqlite.editProduct(product, (String)nameFld.getText(), Integer.parseInt(stockFld.getText()), Double.parseDouble(priceFld.getText()));
                    this.init();
                } 
            }
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void checkProduct(String pName, String pStock, String pPrice){
        
        boolean isNameValid = false;
        boolean isStockValid = false;
        boolean isPriceValid = false;
        boolean isNameUnique = true;

        // Checks if the product name is valid so it must not contain <, >, ', or "
        Pattern patternName = Pattern.compile("^[^<>'\"]+$");
        Matcher matcherName = patternName.matcher(pName);
        boolean containsName = matcherName.find();
        
        // Checks if the product stock is valid
        Pattern patternStock = Pattern.compile("^[1-9]\\d*$");
        Matcher matcherStock = patternStock.matcher(pStock);
        boolean containsStock = matcherStock.find();
        
        // Checks if the product price is valid
        Pattern patternPrice = Pattern.compile("\\d+(,\\d{3})*(\\.\\d{1,2})?$");
        Matcher matcherPrice = patternPrice.matcher(pPrice);
        boolean containsPrice = matcherPrice.find();       
                
        // Sets the text for the error message
        if(containsName == false && containsStock == false && containsPrice == false){
            JOptionPane.showMessageDialog(null, "Invalid product name, stock, and price.", "INPUT ERROR", JOptionPane.ERROR_MESSAGE);
            isProductValValid = false;
        } else if(containsName == true && containsStock == false && containsPrice == false){
            JOptionPane.showMessageDialog(null, "Invalid product stock, and price.", "INPUT ERROR", JOptionPane.ERROR_MESSAGE);
            isProductValValid = false;
        } else if(containsName == false && containsStock == true && containsPrice == false){
            JOptionPane.showMessageDialog(null, "Invalid product name, and price.", "INPUT ERROR", JOptionPane.ERROR_MESSAGE);
            isProductValValid = false;
        } else if(containsName == false && containsStock == false && containsPrice == true){
            JOptionPane.showMessageDialog(null, "Invalid product name, and stock.", "INPUT ERROR", JOptionPane.ERROR_MESSAGE);
            isProductValValid = false;
        } else if(containsName == false && containsStock == true && containsPrice == true){
            JOptionPane.showMessageDialog(null, "Invalid product name.", "INPUT ERROR", JOptionPane.ERROR_MESSAGE);
            isProductValValid = false;
        } else if(containsName == true && containsStock == false && containsPrice == true){
            JOptionPane.showMessageDialog(null, "Invalid product stock.", "INPUT ERROR", JOptionPane.ERROR_MESSAGE);
            isProductValValid = false;
        } else if(containsName == true && containsStock == true && containsPrice == false){
            JOptionPane.showMessageDialog(null, "Invalid product price.", "INPUT ERROR", JOptionPane.ERROR_MESSAGE);
            isProductValValid = false;
        } else {
            isProductValValid = true;
        }
    }
    
    private void checkExistingProduct(int nTask, String newName, String oldName){
        boolean isNameUnique = true;
        
        // ADD PRODUCT: Checks if product name already exists in the database
        if(nTask == 1){
            ArrayList<Product> pList = sqlite.getProduct();
            for(int i = 0; i < pList.size(); i++){
                if(pList.get(i).getName().equalsIgnoreCase(newName)){
                    isNameUnique = false;
                }
            }
        }
        
        // EDIT PRODUCT: Checks if product name already exists in the database
        else if(nTask == 2){
            
            if(!newName.equalsIgnoreCase(oldName)){
                ArrayList<Product> pList = sqlite.getProduct();
                for(int i = 0; i < pList.size(); i++){
                    if(pList.get(i).getName().equalsIgnoreCase(newName)){
                        isNameUnique = false;
                    }
                }
            }
        }
        
        if(!isNameUnique){
            JOptionPane.showMessageDialog(null, "Product already exists.", "INPUT ERROR", JOptionPane.ERROR_MESSAGE);
            isProductValValid = false;
        }
    }
    
    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        if(table.getSelectedRow() >= 0){
            int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete " + tableModel.getValueAt(table.getSelectedRow(), 0) + "?", "DELETE PRODUCT", JOptionPane.YES_NO_OPTION);
            
            if (result == JOptionPane.YES_OPTION) {
                System.out.println(tableModel.getValueAt(table.getSelectedRow(), 0));
                sqlite.deleteProduct(sqlite.getProduct((String)tableModel.getValueAt(table.getSelectedRow(), 0)));
                this.init();
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton purchaseBtn;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
